apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaskdemo2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flaskdemo2
  template:
    metadata:
      labels:
        app: flaskdemo2
    spec:
      containers:
      - name: flaskdemo2
        image: linuxgray039/test:18
        ports:
        - containerPort: 5000

