apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaskdemo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flaskdemo
  template:
    metadata:
      labels:
        app: flaskdemo
    spec:
      containers:
      - name: flaskdemo
        image: linuxgray039/test:6
        ports:
        - containerPort: 5000

